### ISSUE TITLE
Does RxJava3 emphasize Flowables more than Observables?

### ISSUE THREAD

**Issue by RobLewis** [akarnokd/RxJavaBridge#50]
Haven't done a deep dive into this, and I apologize for being vague, but in the reading I've done on RxJava3 I seem to see more mentions of Flowables, and less emphasis on Observables. 
Am I completely mistaken, or is there a shift of emphasis? If so, what's the rationale?

**Comment by akarnokd** [comment]
If you understand Flowables, you can more easily derive the other types by leaving out properties such as backpressure and multiple values over time.

**Comment by RobLewis** [comment]
I think I understand Flowables OK, was just wondering if there was a programming philosophy change that encouraged using them over Observables. Seems like in earlier RxJava versions there was greater emphasis on Observables.

**Comment by akarnokd** [comment]
Historically, [we explained Flowable vs Observable](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#observable-and-flowable) back in the day.

Flowable is bounded in terms of memory usage so it is less likely to create OOME just because someone went from `range(1, 10)` to `range(1, 1_000_000_000)`.
